name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out sources
      uses: actions/checkout@v3
    - run: echo "The ${{ github.repository }} repo has been cloned to ."
    - name: List files
      run: ls ${{ github.workspace }}
    - name: Run l4check
      run: ./make 'TEMPLATE_FILTER=arm64-virt-el1 amd64-1' -j -l 22 l4check
