name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install cross compiler toolchain
      uses: cyberjunk/gha-ubuntu-cross@v4
      with:
        arch: arm64 armhf
    - uses: actions/checkout@v4.1.1
    - name: make
      run: make 'TEMPLATE_FILTER=amd64-1 arm64-virt-el2' -j -l 22 l4check
