name: Mips

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install cross compiler toolchains
      run: sudo apt-get install gcc-mipsel-linux-gnu g++-mipsel-linux-gnu gcc-10-mipsel-linux-gnu g++-10-mipsel-linux-gnu
    - uses: actions/checkout@v4.1.1
    - name: make
      run: make 'TEMPLATE_FILTER=mips-malta-mp mips-malta-64r2-mp' -j -l 22 l4check
