name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo "The ${{ github.repository }} repo has been cloned to ."
      - run: |
          ls ${{ github.workspace }}
      - run: echo "This job's status is ${{ job.status }}."
      - run: ./make 'TEMPLATE_FILTER=amd64-1' -j -l 22 l4check
